import { readFileSync } from "node:fs";
import {
  type PolicyMaskingKind,
  type PolicySchemaNode,
  policyMaskingKinds,
  policyProfileInputSchema,
} from "../generated/policy-schema.gen.js";

/**
 * Policy authoring helpers shared by `policies create` and `policies update`:
 * repeatable flag collection, `--mask table.column=kind` parsing, and
 * client-side validation of policy bodies against the contract-derived schema
 * in generated/policy-schema.gen.ts (regenerated by `pnpm generate:cli`, so it
 * cannot drift from the API).
 */

/** A single parsed masking rule from a `--mask table.column=kind` flag. */
export interface ParsedMaskRule {
  table: string;
  column: string;
  kind: PolicyMaskingKind;
}

function isMaskingKind(kind: string): kind is PolicyMaskingKind {
  return (policyMaskingKinds as readonly string[]).includes(kind);
}

/**
 * Collect every value of a repeatable string flag. citty's parser keeps only
 * the last occurrence of a repeated flag, so repeated occurrences are read from
 * the raw argv when available; the parsed value is the fallback (and covers
 * tests that call `run()` without rawArgs). Each collected value is also split
 * on commas, so `--allow a --allow b` and `--allow a,b` are equivalent.
 */
export function collectRepeatable(
  name: string,
  rawArgs: readonly string[] | undefined,
  parsed: string | boolean | string[] | undefined,
): string[] {
  const values: string[] = [];
  if (rawArgs) {
    for (let i = 0; i < rawArgs.length; i++) {
      const arg = rawArgs[i];
      if (arg === `--${name}`) {
        const next = rawArgs[i + 1];
        if (typeof next === "string" && !next.startsWith("--")) {
          values.push(next);
          i++;
        }
      } else if (arg.startsWith(`--${name}=`)) {
        values.push(arg.slice(name.length + 3));
      }
    }
  }
  if (values.length === 0) {
    if (Array.isArray(parsed)) {
      for (const v of parsed) if (typeof v === "string") values.push(v);
    } else if (typeof parsed === "string") {
      values.push(parsed);
    }
  }
  return values.flatMap((v) => v.split(",").map((s) => s.trim())).filter((s) => s.length > 0);
}

/** Whether a repeatable flag was passed at all (even with an empty value). */
export function hasRepeatable(
  name: string,
  rawArgs: readonly string[] | undefined,
  parsed: string | boolean | string[] | undefined,
): boolean {
  if (rawArgs?.some((arg) => arg === `--${name}` || arg.startsWith(`--${name}=`))) {
    return true;
  }
  return parsed !== undefined && typeof parsed !== "boolean";
}

/**
 * Parse a `--mask table.column=kind` value. The table may be schema-qualified
 * (`public.users.email=redact`); the segment after the last dot is the column.
 * The kind is validated against the contract's masking kinds.
 */
export function parseMaskFlag(value: string): ParsedMaskRule {
  const eq = value.indexOf("=");
  if (eq === -1) {
    throw new Error(
      `Invalid --mask "${value}": expected table.column=kind (e.g. users.email=redact).`,
    );
  }
  const target = value.slice(0, eq).trim();
  const kind = value.slice(eq + 1).trim();
  const lastDot = target.lastIndexOf(".");
  if (lastDot <= 0 || lastDot === target.length - 1) {
    throw new Error(
      `Invalid --mask "${value}": expected table.column=kind (e.g. users.email=redact).`,
    );
  }
  if (!isMaskingKind(kind)) {
    throw new Error(
      `Invalid --mask kind "${kind}" for "${target}". Allowed kinds: ${policyMaskingKinds.join(", ")}.`,
    );
  }
  return { table: target.slice(0, lastDot), column: target.slice(lastDot + 1), kind };
}

/** Read and parse a `--file` JSON policy body, with clear failure messages. */
export function readPolicyFile(path: string, flagName = "--file"): Record<string, unknown> {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Could not read ${flagName} ${path}: ${message}`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`${flagName} ${path} is not valid JSON: ${message}`);
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(`${flagName} ${path} must contain a JSON object with policy profile fields.`);
  }
  return parsed as Record<string, unknown>;
}

/**
 * Read, parse, and schema-validate a `--draft` policy file for dry-eval and
 * replay. Runs entirely client-side so a bad path or body fails before any
 * auth resolution or network call. A draft need not be named (the API supplies
 * a placeholder), so a missing name is tolerated here too.
 */
export function readDraftPolicyFile(path: string): Record<string, unknown> {
  const parsed = readPolicyFile(path, "--draft");
  const name = parsed.name;
  const forValidation =
    typeof name === "string" && name.trim() !== "" ? parsed : { ...parsed, name: "draft" };
  assertValidPolicyInput(forValidation, `--draft ${path}`);
  return parsed;
}

/**
 * Validate a policy profile body against the contract-derived
 * PolicyProfileInput schema. Returns a list of problems (empty when valid).
 */
export function validatePolicyInput(value: unknown): string[] {
  return validateNode(value, policyProfileInputSchema, "policy");
}

/**
 * Validate a policy body and throw a single readable error listing every
 * problem when it is invalid.
 */
export function assertValidPolicyInput(value: unknown, source: string): void {
  const problems = validatePolicyInput(value);
  if (problems.length > 0) {
    throw new Error(
      `Invalid policy profile (${source}):\n${problems.map((p) => `  - ${p}`).join("\n")}`,
    );
  }
}

function validateNode(value: unknown, schema: PolicySchemaNode, path: string): string[] {
  const problems: string[] = [];

  if (schema.type === "object" || schema.properties) {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return [`${path}: expected an object.`];
    }
    const record = value as Record<string, unknown>;
    for (const key of schema.required ?? []) {
      if (record[key] === undefined) {
        problems.push(`${path}.${key}: required field is missing.`);
      }
    }
    for (const [key, child] of Object.entries(record)) {
      if (child === undefined) continue;
      const childSchema = schema.properties?.[key];
      if (!childSchema) {
        const known = Object.keys(schema.properties ?? {}).join(", ");
        problems.push(`${path}.${key}: unknown field. Known fields: ${known}.`);
        continue;
      }
      problems.push(...validateNode(child, childSchema, `${path}.${key}`));
    }
    return problems;
  }

  if (schema.type === "array") {
    if (!Array.isArray(value)) {
      return [`${path}: expected an array.`];
    }
    if (schema.items) {
      value.forEach((item, i) => {
        problems.push(...validateNode(item, schema.items as PolicySchemaNode, `${path}[${i}]`));
      });
    }
    return problems;
  }

  if (schema.type === "string") {
    if (typeof value !== "string") {
      return [`${path}: expected a string.`];
    }
    if (schema.enum && !schema.enum.includes(value)) {
      problems.push(`${path}: "${value}" is not one of ${schema.enum.join(", ")}.`);
    }
    if (schema.minLength !== undefined && value.length < schema.minLength) {
      problems.push(`${path}: must be at least ${schema.minLength} character(s).`);
    }
    if (schema.maxLength !== undefined && value.length > schema.maxLength) {
      problems.push(`${path}: must be at most ${schema.maxLength} characters.`);
    }
    return problems;
  }

  if (schema.type === "integer" || schema.type === "number") {
    if (typeof value !== "number" || Number.isNaN(value)) {
      return [`${path}: expected a number.`];
    }
    if (schema.type === "integer" && !Number.isInteger(value)) {
      problems.push(`${path}: expected an integer.`);
    }
    if (schema.minimum !== undefined && value < schema.minimum) {
      problems.push(`${path}: must be at least ${schema.minimum}.`);
    }
    return problems;
  }

  if (schema.type === "boolean" && typeof value !== "boolean") {
    return [`${path}: expected a boolean.`];
  }

  return problems;
}
